export const welcome = [
  '# 阅读，从这里开始 · Start reading here',
  '',
  '一份笔记、一篇长文，或一个刚刚下载的 README。把 Markdown 文件拖进来，让文字回到清晰、舒适的样子。\n\nA note, a long-form essay, or a README you just downloaded. Drop a Markdown file here and give the words a clear, comfortable surface.',
  '',
  '> 慢一点，把一段话读完，把一个想法想清楚。',
  '',
  '## 打开你的第一份文档 · Open your first document',
  '',
  '点击左侧 **打开文件**，或直接把 `.md` 文件拖到窗口中。也可以点击 **粘贴文本**，阅读剪贴板中的 Markdown。\n\nChoose **Open file** on the left, or drag a `.md` file into the window. You can also choose **Paste text** to read Markdown from the clipboard.',
  '',
  '可以一次打开多份文档，在左侧来回切换。文档只在本机读取。可从“文件 → 最近打开”重新打开文档，按 F5 读取外部修改；字体、主题和语言设置会保留。',
  '',
  '## 找到舒服的阅读节奏 · Find your reading rhythm',
  '',
  '右上角的 **Aa** 可以调整字号、行距、字体和正文宽度。点击专注模式，收起两侧栏，只留下文字。右侧目录会跟随阅读位置，也可以点击标题直接跳转。\n\nUse **Aa** in the top-right corner to adjust type size, line height, font, and page width. Focus mode clears the sidebars. The table of contents follows your position and lets you jump between headings.',
  '',
  '### 一点点恰好的排版',
  '',
  '**重要的内容**可以加粗，*轻轻的强调*可以用斜体，~~已经过时的想法~~也可以留在笔记里。行内代码 `readme.md` 会和正文自然地区分开。',
  '',
  '切换到 **源码**，可以随时查看文档原本的 Markdown。**Ctrl + F** 可以查找文中的文字。',
  '',
  '## 表格、代码与公式 · Tables, code, and math',
  '',
  '阅读技术笔记时，结构和细节同样重要。',
  '',
  '| 内容 | 支持的格式 |',
  '| :--- | :--- |',
  '| 日常笔记 | 标题、引用、列表、链接 |',
  '| 项目文档 | 代码高亮、表格、任务清单 |',
  '| 科研笔记 | LaTeX 数学公式、Mermaid 流程图 |',
  '',
  '### 让代码更容易读',
  '',
  '代码块支持语法高亮，也可以一键复制。长行可以横向滚动，不会挤压正文。',
  '',
  '```python',
  'from pathlib import Path',
  '',
  'def read_note(filename: str) -> str:',
  '    return Path(filename).read_text(encoding="utf-8")',
  '',
  'note = read_note("今天的笔记.md")',
  'print(note)',
  '```',
  '',
  '### 数学，也可以好好排版',
  '',
  '行内公式，例如 $E = mc^2$，可以直接融入段落。较长的推导则独立成行：',
  '',
  '$$',
  '\\operatorname{Attention}(Q,K,V) = \\operatorname{softmax}\\left(\\frac{QK^{\\mathsf{T}}}{\\sqrt{d_k}}\\right)V',
  '$$',
  '',
  '## 用图理清一个思路 · Make an idea visible',
  '',
  'Mermaid 代码会自动显示为图。下面是一个简单的阅读与整理过程：',
  '',
  '```mermaid',
  'flowchart TD',
  '  A[阅读一份文档] --> B{是否理解？}',
  '  B -->|是| C[记录关键想法]',
  '  B -->|还没有| D[回到相关章节]',
  '  D --> A',
  '  C --> E[连接已有知识]',
  '```',
  '',
  '## 留下一个小小的清单 · Leave a small checklist',
  '',
  '- [x] 为一份长文找到舒服的排版',
  '- [x] 用目录，在想法之间自由跳转',
  '- [ ] 打开自己的第一份 Markdown',
  '',
  '如果文档引用了本地图片，把对应图片一并拖进窗口即可。网络图片需要联网；文件内容不会上传。',
  '',
  '---',
  '',
  '现在，打开一份想读的文档吧。',
].join('\n');

export const formatGuide = [
  '# Markdown 格式速查 · Markdown quick reference', '',
  '这是一份可以边读边对照的简短参考。切到 **源码**，就能看到这些格式的写法。\n\nA short reference to read beside your notes. Switch to **Source** to see the original Markdown syntax.', '',
  '## 标题与段落 · Headings and paragraphs', '',
  '以一个到六个 `#` 加空格开头，可以生成不同层级的标题。两个段落之间留一个空行。\n\nStart with one to six `#` characters and a space to create heading levels. Leave a blank line between paragraphs.', '',
  '## 文字强调 · Text emphasis', '',
  '- **加粗**：两侧使用两个星号。',
  '- *斜体*：两侧使用一个星号。',
  '- ~~删除线~~：两侧使用两个波浪号。',
  '- `行内代码`：两侧使用反引号。', '',
  '## 引用与列表 · Quotes and lists', '',
  '> 引用可以保存一段值得记住的话。', '',
  '1. 先明确这份文档想回答什么。',
  '2. 找出关键论点和支持它的证据。',
  '3. 再整理自己的判断与疑问。', '',
  '## 任务清单 · Task lists', '',
  '- [x] 阅读摘要', '- [ ] 检查实验设置', '- [ ] 记录后续问题', '',
  '## 表格 · Tables', '',
  '| 写法 | 用途 |', '| --- | --- |',
  '| `# 标题` | 一级标题 |', '| `**文字**` | 加粗 |',
  '| `[名称](https://example.com)` | 超链接 |', '| `![描述](image.png)` | 图片 |', '',
  '## 代码块 · Code blocks', '',
  '使用三个反引号包围代码，在第一行标注语言可以显示高亮。', '',
  '```javascript', 'const title = "一份值得读的笔记";', 'console.log(title);', '```', '',
  '## 公式 · Math', '',
  '用一个美元符号包围行内公式：$x^2 + y^2 = z^2$。', '',
  '用两个美元符号包围独立公式：', '', '$$',
  '\\bar{x} = \\frac{1}{n}\\sum_{i=1}^{n}x_i', '$$', '',
  '## 本地文件与图片 · Local files and images', '',
  '支持 UTF-8、带 BOM 的 UTF-16，以及常见 GB18030 中文编码。可以打开 `.md`、`.markdown`、`.mdown` 和 `.txt` 文件。', '',
  '将图片与文档一同打开或拖入后，相对引用按图片文件名匹配。同名图片请先重命名。刷新页面后，需要重新打开文档与图片。', '',
  '## 快捷操作 · Shortcuts', '',
  '| 快捷键 | 操作 |', '| --- | --- |',
  '| Ctrl / ⌘ + O | 打开本地文件 |',
  '| Ctrl / ⌘ + B | 显示或收起文件栏 |',
  '| Ctrl / ⌘ + F | 查找文档内容 |',
  '| Esc | 退出专注模式 |',
].join('\n');
